name: Deploy WordPress Theme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Deploy via SFTP
      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@4.4.0
        with:
          server: 188.166.38.114
          username: ploi
          protocol: sftp
          local-dir: ./wp-theme-folder
          server-dir: /home/ploi/public_html/wp-content/themes/your-theme-folder
